% Script generated by antennaDesigner 
% Define plot frequency 
plotFrequency = 11700000000;
% Define frequency range 
freqRange = (10.53:0.117:12.87) * 1e9;
% Define antenna 
antennaObject = patchMicrostrip_antennaDesigner;
% show for patchMicrostrip
figure;
show(antennaObject) 
% current for patchMicrostrip
figure;
current(antennaObject, plotFrequency) 
% pattern for patchMicrostrip
figure;
pattern(antennaObject, plotFrequency) 
% s11 for patchMicrostrip
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s) 

